name: Review Instance
on: 
  workflow_dispatch:
    inputs:
      devops_branch:
        description: 'devops branch'     
        required: true
        default: 'master'
      api_branch:
        description: 'vets-api branch'
        required: true
        default: 'master'
      web_branch:
        description: 'vets-website branch'
        required: true
        default: 'main'
      content_branch:
        description: 'content-build branch'
        required: true
        default: 'main'
      tags:
        description: 'Test scenario tags'

jobs:
  env-setup:
    name: ENV SETUP
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-gov-west-1"

      - name: Obtain GitHub Token
        uses: marvinpinto/action-inject-ssm-secrets@latest
        with:
          ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
          env_variable_name: VA_VSP_BOT_GITHUB_TOKEN

      - name: Clone devops repo
        uses: actions/checkout@v2
        with:
         repository: department-of-veterans-affairs/devops
         ref: master
         token: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}

